version: '3.8'
services:
  strava-running-bot:
    image: "ghcr.io/${GITHUB_REPOSITORY_OWNER:-your-gh-user}/strava-running-bot:latest"
    container_name: strava-running-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - bot_data:/app/data
      - ./logs:/app/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  bot_data:
    driver: local
