name: Build and publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch: {}   # allow manual runs from the Actions UI

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up QEMU for multi-arch emulation (optional but recommended)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Ensure a container-based buildx builder is created so cache export (--cache-to) is supported
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/strava-running-bot:latest
            ghcr.io/${{ github.repository_owner }}/strava-running-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
